# Generated by Django 3.2.9 on 2022-02-01 07:01

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=30)),
                ('review', models.TextField(max_length=1000)),
                ('rating', models.CharField(max_length=5)),
                ('ondate', models.DateTimeField(default=datetime.datetime(2022, 2, 1, 12, 1, 32, 837412), verbose_name=datetime.datetime)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('discount', models.IntegerField(max_length=2)),
                ('available', models.BooleanField(default=False)),
                ('warranty', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_heading_one', models.CharField(max_length=40)),
                ('product_image_one', models.ImageField(upload_to='')),
                ('product_description_one', models.TextField(max_length=700)),
                ('product_heading_two', models.CharField(max_length=40)),
                ('product_image_two', models.ImageField(upload_to='')),
                ('product_description_two', models.TextField(max_length=700)),
                ('product_heading_three', models.CharField(max_length=40)),
                ('product_image_three', models.ImageField(upload_to='')),
                ('product_description_three', models.TextField(max_length=700)),
                ('product_heading_four', models.CharField(max_length=40)),
                ('product_image_four', models.ImageField(upload_to='')),
                ('product_description_four', models.TextField(max_length=700)),
                ('product_heading_five', models.CharField(max_length=40)),
                ('product_image_five', models.ImageField(upload_to='')),
                ('product_description_five', models.TextField(max_length=700)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Additional_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
