# Generated by Django 3.2.9 on 2022-02-01 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_review_ondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 13, 2, 52, 289114), verbose_name=datetime.datetime),
        ),
    ]
