# Generated by Django 3.2.9 on 2022-02-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review_ondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 17, 35, 29, 141199), verbose_name=datetime.datetime),
        ),
    ]
