# Generated by Django 3.2.9 on 2022-02-03 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220203_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_address',
            new_name='street_address1',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='street_address2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 14, 50, 46, 901587), verbose_name=datetime.datetime),
        ),
    ]
