# Generated by Django 3.2.9 on 2022-02-04 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220203_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField(max_length=1999)),
                ('expired_date', models.DateTimeField(default=datetime.datetime(2022, 2, 4, 13, 10, 30, 238563), verbose_name=datetime.datetime)),
                ('csc', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 13, 10, 30, 234959), verbose_name=datetime.datetime),
        ),
    ]
