# Generated by Django 3.2.9 on 2022-02-04 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220204_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expired_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_month',
            field=models.CharField(default='MM', max_length=2),
        ),
        migrations.AddField(
            model_name='payment',
            name='expired_year',
            field=models.CharField(default='YY', max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 14, 51, 16, 891889), verbose_name=datetime.datetime),
        ),
    ]
