# Generated by Django 3.2.9 on 2022-02-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220204_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 22, 31, 8, 912447), verbose_name=datetime.datetime),
        ),
    ]
