# Generated by Django 4.0.2 on 2022-02-07 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220207_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='csc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 22, 3, 42, 806590), verbose_name=datetime.datetime),
        ),
    ]
