# Generated by Django 4.0.2 on 2022-02-09 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_cart_single_total_alter_review_ondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 12, 40, 3, 875915), verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='shopinghistory',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
