# Generated by Django 4.0.2 on 2022-02-09 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_review_ondate_alter_shopinghistory_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 12, 56, 59, 939632), verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='shopinghistory',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
